### ISSUE TITLE
StringIndexOutOfBoundsException on empty ordered list input.

### ISSUE THREAD

**Issue by jleyba** [atlassian/commonmark-java#13]
Using `com.atlassian.commonmark:commonmark:0.1.0`:

    import static org.junit.Assert.assertEquals;

    import org.commonmark.html.HtmlRenderer;
    import org.commonmark.node.Node;
    import org.commonmark.parser.Parser;
    import org.junit.Test;
    import org.junit.runner.RunWith;
    import org.junit.runners.JUnit4;

    @RunWith(JUnit4.class)
    public class MarkdownTest {
      @Test
      public void shouldWork() {
        Parser parser = Parser.builder().build();
        Node root = parser.parse("2.");

        HtmlRenderer renderer = HtmlRenderer.builder().escapeHtml(false).build();
        String html = renderer.render(root);

        assertEquals(
            "<ol start=\"2\">\n" +
                "<li></li>\n" +
                "</ol>",
            html);
      }
    }

The test above fails with:

    java.lang.StringIndexOutOfBoundsException: String index out of range: 2
      at java.lang.String.charAt(String.java:658)
      at org.commonmark.internal.util.Substring.charAt(Substring.java:32)
      at java.lang.Character.codePointAt(Character.java:4668)
      at org.commonmark.internal.util.Parsing.isLetter(Parsing.java:55)
      at org.commonmark.internal.DocumentParser.incorporateLine(DocumentParser.java:194)
      at org.commonmark.internal.DocumentParser.parse(DocumentParser.java:83)
      at org.commonmark.parser.Parser.parse(Parser.java:45)
      at MarkdownTest.shouldWork(MarkdownTest.java:32)

For reference, here's the output for commonmark.js: [http://spec.commonmark.org/dingus/?text=2.](http://spec.commonmark.org/dingus/?text=2.)

**Edit** Fixed rendering of dingus link

**Comment by robinst** [comment]
Thanks for the report! This has already been fixed by 5a2b3917805eeaf453347443f3e7ba64aa9eba08 on master, but I'll add your test case to make sure there won't be a regression.

**Comment by robinst** [comment]
Fix released in [0.2.0](https://github.com/atlassian/commonmark-java/releases/tag/commonmark-parent-0.2.0).
