### ISSUE TITLE
StringIndexOutOfBoundsException in InlineParserImpl

### ISSUE THREAD

**Issue by JinneeJ** [atlassian/commonmark-java#27]
Attempting to parse the wrong string like this `[example.com](http:\\example.com` leads to the following exception:
```
java.lang.StringIndexOutOfBoundsException: length=32; index=32
            at java.lang.String.charAt(Native Method)
            at org.commonmark.internal.InlineParserImpl.parseCloseBracket(InlineParserImpl.java:579)
            at org.commonmark.internal.InlineParserImpl.parseInline(InlineParserImpl.java:303)
            at org.commonmark.internal.InlineParserImpl.parse(InlineParserImpl.java:157)
            at org.commonmark.internal.ParagraphParser.parseInlines(ParagraphParser.java:61)
            at org.commonmark.internal.DocumentParser.processInlines(DocumentParser.java:349)
            at org.commonmark.internal.DocumentParser.finalizeAndProcess(DocumentParser.java:495)
            at org.commonmark.internal.DocumentParser.parse(DocumentParser.java:84)
            at org.commonmark.parser.Parser.parse(Parser.java:61)
```

**Comment by robinst** [comment]
Hey there! Sorry for the slow response (I was on holidays).

I just pushed a commit that fixes it, see reference above. I also added an integration test that would have caught that case. I'll release a point release with the fix shortly.

Thanks for reporting!

**Comment by JinneeJ** [comment]
Thank you!

**Comment by robinst** [comment]
There's currently a problem in how the sync to Maven Central is set up on our end, which prevents the release from being available on Maven Central. I'll update this as soon as it's out!

**Comment by robinst** [comment]
Ok, version 0.3.1 with the fix is finally out :).
